SREA/Controllers/SalonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SREA.Models;

namespace SREA.Controllers
{
    public class SalonesController : Controller
    {
        private SREAContext db = new SREAContext();

        public ActionResult GeneratePDF()
        {
            return new Rotativa.ActionAsPdf("Lista");
        }

        // GET: Salones
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            var salons = db.Salons.Include(s => s.Edificio);
            return View(salons.ToList());
        }

        public ActionResult Modificar()
        {
            var salons = db.Salons.Include(s => s.Edificio);
            return View(salons.ToList());
        }

        // GET: Salones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon salon = db.Salons.Find(id);
            if (salon == null)
            {
                return HttpNotFound();
            }
            return View(salon);
        }

        // GET: Salones/Create
        public ActionResult Create()
        {
            ViewBag.ID_Edificio = new SelectList(db.Edificios, "ID_Edificio", "Nombre");
            return View();
        }

        // POST: Salones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Salon,Nombre,Capacidad,Descripcion,ID_Edificio")] Salon salon)
        {
            if (ModelState.IsValid)
            {
                db.Salons.Add(salon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Edificio = new SelectList(db.Edificios, "ID_Edificio", "Nombre", salon.ID_Edificio);
            return View(salon);
        }

        // GET: Salones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon salon = db.Salons.Find(id);
            if (salon == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Edificio = new SelectList(db.Edificios, "ID_Edificio", "Nombre", salon.ID_Edificio);
            return View(salon);
        }

        // POST: Salones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Salon,Nombre,Capacidad,Descripcion,ID_Edificio")] Salon salon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Edificio = new SelectList(db.Edificios, "ID_Edificio", "Nombre", salon.ID_Edificio);
            return View(salon);
        }

        // GET: Salones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salon salon = db.Salons.Find(id);
            if (salon == null)
            {
                return HttpNotFound();
            }
            return View(salon);
        }

        // POST: Salones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Salon salon = db.Salons.Find(id);
            db.Salons.Remove(salon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SREA/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SREA.Models;

namespace SREA.Controllers
{
    public class SolicitudesController : Controller
    {
        private SREAContext db = new SREAContext();

        public ActionResult GeneratePDF()
        {
            return new Rotativa.ActionAsPdf("Lista");
        }

        // GET: Solicitudes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            var solicituds = db.Solicituds.Include(s => s.Persona).Include(s => s.Salon);
            return View(solicituds.ToList());
        }

        public ActionResult Modificar()
        {
            try
            {
                if (Session["ID_Persona"] != null)
                {
                    var solicituds = db.Solicituds.Include(s => s.Persona).Include(s => s.Salon);
                    return View(solicituds.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "Home");

                }
            }catch(Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        //.Where(x => x.ID_Persona == (int)Session["ID_Persona"])
        // GET: Solicitudes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicituds.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // GET: Solicitudes/Create
        public ActionResult Create()
        {
            if (Session["Nick"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ID_Persona = new SelectList(db.Personas, "ID_Persona", "Nick");
                ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre");
                return View();
            }
            
        }

        // POST: Solicitudes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Solicitud,Tema,Cantidad_Inscritos,Fecha_Solicitud,Estado,ID_Salon,ID_Persona")] Solicitud solicitud)
        {
            if (Session["Nick"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var consulta = db.Salons.Find(solicitud.ID_Salon);
                    
                    if (Session["Privilegio"].Equals("3"))
                    {
                        if (consulta.Capacidad >= solicitud.Cantidad_Inscritos)
                        {
                            db.Solicituds.Add(solicitud);
                            db.SaveChanges();
                            return RedirectToAction("Create", "Dia_Apartado");
                        }
                        
                    }
                    else
                    {
                       

                        if (consulta.Capacidad >= solicitud.Cantidad_Inscritos)
                        {
                            db.Solicituds.Add(solicitud).ID_Persona = Convert.ToInt16(Session["ID_Persona"]);
                            db.Solicituds.Add(solicitud).Estado = false;
                            db.SaveChanges();
                            return RedirectToAction("Create", "Dia_Apartado");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Salon no tiene esa capacidad");
                        }
                        
                    }
                    
                    
                }

                ViewBag.ID_Persona = new SelectList(db.Personas, "ID_Persona", "Nick", solicitud.ID_Persona);
                ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", solicitud.ID_Salon);
                return View(solicitud);
            }

            
        }

        // GET: Solicitudes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Nick"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Solicitud solicitud = db.Solicituds.Find(id);
                if (solicitud == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ID_Persona = new SelectList(db.Personas, "ID_Persona", "Nick", solicitud.ID_Persona);
                ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", solicitud.ID_Salon);
                return View(solicitud);
            }
           
        }

        // POST: Solicitudes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Solicitud,Tema,Cantidad_Inscritos,Fecha_Solicitud,Estado,ID_Salon,ID_Persona")] Solicitud solicitud)
        {
            if (Session["Nick"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (ModelState.IsValid)
                {

                    if (Session["Privilegio"].Equals("3"))
                    {
                        db.Entry(solicitud).State = EntityState.Modified;
                    }
                    else
                    {
                        solicitud.ID_Persona = Convert.ToInt16(Session["ID_Persona"]);
                        solicitud.Estado = false;
                        db.Entry(solicitud).State = EntityState.Modified;
                    }
                    db.Entry(solicitud).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_Persona = new SelectList(db.Personas, "ID_Persona", "Nick", solicitud.ID_Persona);
                ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", solicitud.ID_Salon);
                return View(solicitud);
            }
           
        }

        // GET: Solicitudes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicituds.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // POST: Solicitudes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solicitud solicitud = db.Solicituds.Find(id);
            db.Solicituds.Remove(solicitud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SREA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="row expandir" style="width:100%; background-color: white;">
        <div class="container" style="text-align:center;">
            <img src="~/Content/img/encabezado.jpg" style="width: 70%;" />
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #003b36; position: relative;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Como Funciona", "About", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Salones<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li>@Html.ActionLink("Listado del Espacio Academico", "Lista", "Salones")</li>
                          <li>@Html.ActionLink("Espacio Academico Apartado", "Lista", "Dia_Apartado")</li>
                          @if (Session["ID_Persona"] != null)
                            {
                                <li>@Html.ActionLink("Opciones Para Solicitar El Espacio Academico", "Index", "Solicitudes")</li>
                                <li>@Html.ActionLink("Mis Dia de Reserva", "Index", "Dia_Apartado")</li>                       

                          }
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Quienes Somos", "About", "Home")</li>
                    <li>@Html.ActionLink("Contactenos", "Create", "Contactenos")</li>

                    @if (Session["ID_Persona"] == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Personas")</li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenido @Session["Nombre_Usuario"].ToString()<b class="caret"></b></a>
                            <ul class="dropdown-menu">  
                                @if (Session["Privilegio"].Equals("3"))
                                {
                                    <li>@Html.ActionLink("Administrar", "Administrar", "Personas")</li>
                                }
                                @if (Session["ID_Persona"] != null)
                                {
                                    <li>@Html.ActionLink("Login out", "LoginOut", "Personas")</li>
                                }

                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <br />

    <br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="background-color: #003b36">
            <div class="row">
                <div class="container" style="text-align: center;">
                    
                    <font color="white">Sede Principal Fusagasugá - Diagonal 18 No. 20-29 PBX 1-828 1483 - Fax 1-8732554 - email: unicundi@mail.unicundi.edu.co</font><br>
                    <font color="white">Institución de Educación Superior Sujeta a Inspección y Vigilancia por el Ministerio de Educación Nacional </font>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>