SREA/Models/Inventario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SREA.Models
{
    public class Inventario
    {
        [Key]
        public int ID_Inventario { get; set; }

        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [StringLength(30, ErrorMessage = "El campo {0} debe estar entre {2} y {1} carácteres", MinimumLength = 3)]
        public string Descripcion { get; set; }

        [Display(Name = "Cantidad en el Inventario")]
        [Required(ErrorMessage = "Debes ingresar un {0}")]
        [Range(1, 100, ErrorMessage = "Debe ingresar un valor de 1 a 100")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Count must be a natural number")]
        public int Cantidad { get; set; }

        public int ID_Salon { get; set; }
        public virtual Salon Salon { get; set; }

        public int ID_Equipo{ get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}

SREA/Controllers/InventariosController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SREA.Models;

namespace SREA.Controllers
{
    public class InventariosController : Controller
    {
        private SREAContext db = new SREAContext();

        // GET: Inventarios
        public ActionResult Index()
        {
           return View();
        }

        public ActionResult Lista()
        {
            var inventarios = db.Inventarios.Include(i => i.Equipo).Include(i => i.Salon);
            return View(inventarios.ToList());
        }

        public ActionResult Modificar()
        {
            var inventarios = db.Inventarios.Include(i => i.Equipo).Include(i => i.Salon);
            return View(inventarios.ToList());
        }

        // GET: Inventarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventario inventario = db.Inventarios.Find(id);
            if (inventario == null)
            {
                return HttpNotFound();
            }
            return View(inventario);
        }

        // GET: Inventarios/Create
        public ActionResult Create()
        {
            ViewBag.ID_Equipo = new SelectList(db.Equipoes, "ID_Equipo", "Tipo_Equipo");
            ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre");
            return View();
        }

        // POST: Inventarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Inventario,Descripcion,Cantidad,ID_Salon,ID_Equipo")] Inventario inventario)
        {
            if (ModelState.IsValid)
            {
                db.Inventarios.Add(inventario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Equipo = new SelectList(db.Equipoes, "ID_Equipo", "Tipo_Equipo", inventario.ID_Equipo);
            ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", inventario.ID_Salon);
            return View(inventario);
        }

        // GET: Inventarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventario inventario = db.Inventarios.Find(id);
            if (inventario == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Equipo = new SelectList(db.Equipoes, "ID_Equipo", "Tipo_Equipo", inventario.ID_Equipo);
            ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", inventario.ID_Salon);
            return View(inventario);
        }

        // POST: Inventarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Inventario,Descripcion,Cantidad,ID_Salon,ID_Equipo")] Inventario inventario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Equipo = new SelectList(db.Equipoes, "ID_Equipo", "Tipo_Equipo", inventario.ID_Equipo);
            ViewBag.ID_Salon = new SelectList(db.Salons, "ID_Salon", "Nombre", inventario.ID_Salon);
            return View(inventario);
        }

        // GET: Inventarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventario inventario = db.Inventarios.Find(id);
            if (inventario == null)
            {
                return HttpNotFound();
            }
            return View(inventario);
        }

        // POST: Inventarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Inventario inventario = db.Inventarios.Find(id);
            db.Inventarios.Remove(inventario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SREA/Views/Inventarios/Create.cshtml
@model SREA.Models.Inventario

@{
    ViewBag.Title = "Create";
}

<h2>Añadir Inventario</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Salon, "Nombre del Salón", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Salon", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Salon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Equipo, "Nombre del Edificio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Equipo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Equipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Inventarios")'">Regresar</button>
</div>

SREA/Views/Inventarios/Details.cshtml
@model SREA.Models.Inventario

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Equipo.Tipo_Equipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipo.Tipo_Equipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salon.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salon.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Regresar", "Lista")
</p>

SREA/Views/Inventarios/Edit.cshtml
@model SREA.Models.Inventario

@{
    ViewBag.Title = "Inventario - Editar";
}

<h2>Editar la Informacion del Inventario</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Inventario)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Salon, "ID_Salon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Salon", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Salon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Equipo, "ID_Equipo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Equipo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Equipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Inventarios")'">Regresar</button>
</div>

SREA/Views/Inventarios/Index.cshtml
@model SREA.Models.Inventario

@{
    ViewBag.Title = "Inventario - Inicio";
}

<h2>Inicio</h2>

<h4>Inventario</h4>

<font>En esta Seccion se podra consultar, ingresar, editar y borrar los Inventarios(Activos) que se encuentran en cada Salón o Laboratorio</font>
<hr />
<ul class="list-group">
    <li class="list-group-item active list-group-item-heading"><span class="glyphicon glyphicon-cog"></span><font color="white"> Salones y Laboratorios</font></li>
    <li class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span>@Html.ActionLink(" Listado del Inventario", "Lista", "Inventarios")</li>
    <li class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>@Html.ActionLink(" Agregar Inventario", "Create", "Inventarios")</li>
    <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span>@Html.ActionLink(" Modificar o Eliminar Registro del Inventario", "Modificar", "Inventarios")</li>
</ul>

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Administrar", "Personas")'">Regresar</button>
</div>

SREA/Views/Inventarios/Lista.cshtml
@model IEnumerable<SREA.Models.Inventario>

@{
    ViewBag.Title = "Lista";
}
<h2>Listado del Inventario</h2>


<table class="table">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.Equipo.Tipo_Equipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salon.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            Opciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Equipo.Tipo_Equipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salon.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID_Inventario })

            </td>
        </tr>
    }

</table>

<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Inventarios")'">Regresar</button>

SREA/Views/Inventarios/Modificar.cshtml
@model IEnumerable<SREA.Models.Inventario>

@{
    ViewBag.Title = "Inventario - Modificar";
}

<h2>Modificar el Inventario</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Equipo.Tipo_Equipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salon.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Equipo.Tipo_Equipo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salon.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID_Inventario }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.ID_Inventario })
        </td>
    </tr>
}

</table>

<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Inventarios")'">Regresar</button>