SREA/Models/Dia_Apartado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SREA.Models
{
    public class Dia_Apartado
    {
        [Key]
        public int ID_Dia_Apartado { get; set; }

        [Display(Name = "Fecha en que desea reservar")]
        [DataType(DataType.Date)]
        public DateTime Fecha_Apartada { get; set; }

        [Display(Name = "Hora de Inicio")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        [DataType(DataType.Time)]
        public DateTime Hora_Comienzo { get; set; }

        [Display(Name = "Hora de Finalización")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        [DataType(DataType.Time)]
        public DateTime Hora_Terminado { get; set; }

        public int ID_Solicitud { get; set; }
        public virtual Solicitud Solicitud { get; set; }

    }
}

SREA/Controllers/Dia_ApartadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SREA.Models;

namespace SREA.Controllers
{
    public class Dia_ApartadoController : Controller
    {
        private SREAContext db = new SREAContext();

        // GET: Dia_Apartado
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult Lista()
        {
            var dia_Apartado = db.Dia_Apartado.Include(d => d.Solicitud);
            return View(dia_Apartado.ToList());
        }

        public ActionResult Modificar()
        {
            var dia_Apartado = db.Dia_Apartado.Include(d => d.Solicitud);
            return View(dia_Apartado.ToList());
        }

        // GET: Dia_Apartado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dia_Apartado dia_Apartado = db.Dia_Apartado.Find(id);
            if (dia_Apartado == null)
            {
                return HttpNotFound();
            }
            return View(dia_Apartado);
        }

        // GET: Dia_Apartado/Create
        public ActionResult Create()
        {
            ViewBag.ID_Solicitud = new SelectList(db.Solicituds, "ID_Solicitud", "Tema");
            return View();
        }

        // POST: Dia_Apartado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Dia_Apartado,Fecha_Apartada,Hora_Comienzo,Hora_Terminado,ID_Solicitud")] Dia_Apartado dia_Apartado)
        {
            if (ModelState.IsValid)
            {
                var consultaDia = db.Dia_Apartado.Where(x => x.Fecha_Apartada == dia_Apartado.Fecha_Apartada).FirstOrDefault();
                if (consultaDia==null)
                {
                    db.Dia_Apartado.Add(dia_Apartado);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    var fechaInicio = db.Dia_Apartado.Where(x => x.Hora_Comienzo >= dia_Apartado.Hora_Comienzo && x.Hora_Terminado <= dia_Apartado.Hora_Comienzo).FirstOrDefault();
                    if (dia_Apartado.Hora_Comienzo >= dia_Apartado.Hora_Terminado)
                    {
                        ModelState.AddModelError("", "La hora de inicio es mayor a la de finalizacion");
                    }
                    List<Dia_Apartado> consulta = new List<Dia_Apartado>();
                    foreach (var sql in db.Dia_Apartado)
                    {
                        if ((dia_Apartado.Hora_Comienzo < sql.Hora_Comienzo && dia_Apartado.Hora_Terminado > sql.Hora_Terminado) 
                            || (dia_Apartado.Hora_Terminado < sql.Hora_Comienzo) || dia_Apartado.Hora_Comienzo > sql.Hora_Terminado)
                        {
                            db.Dia_Apartado.Add(dia_Apartado);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                       
                    }
                    ModelState.AddModelError("", "Ya existe un espacio academico para esa fecha");

                }
                
            }

            ViewBag.ID_Solicitud = new SelectList(db.Solicituds, "ID_Solicitud", "Tema", dia_Apartado.ID_Solicitud);
            return View(dia_Apartado);
        }

        // GET: Dia_Apartado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dia_Apartado dia_Apartado = db.Dia_Apartado.Find(id);
            if (dia_Apartado == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Solicitud = new SelectList(db.Solicituds, "ID_Solicitud", "Tema", dia_Apartado.ID_Solicitud);
            return View(dia_Apartado);
        }

        // POST: Dia_Apartado/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Dia_Apartado,Fecha_Apartada,Hora_Comienzo,Hora_Terminado,ID_Solicitud")] Dia_Apartado dia_Apartado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dia_Apartado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Solicitud = new SelectList(db.Solicituds, "ID_Solicitud", "Tema", dia_Apartado.ID_Solicitud);
            return View(dia_Apartado);
        }

        // GET: Dia_Apartado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dia_Apartado dia_Apartado = db.Dia_Apartado.Find(id);
            if (dia_Apartado == null)
            {
                return HttpNotFound();
            }
            return View(dia_Apartado);
        }

        // POST: Dia_Apartado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dia_Apartado dia_Apartado = db.Dia_Apartado.Find(id);
            db.Dia_Apartado.Remove(dia_Apartado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SREA/Controllers/EquiposController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SREA.Models;

namespace SREA.Controllers
{
    public class EquiposController : Controller
    {
        private SREAContext db = new SREAContext();

        // GET: Equipos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            return View(db.Equipoes.ToList());
        }

        public ActionResult Modificar()
        {
            return View(db.Equipoes.ToList());
        }

        // GET: Equipos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipo equipo = db.Equipoes.Find(id);
            if (equipo == null)
            {
                return HttpNotFound();
            }
            return View(equipo);
        }

        // GET: Equipos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Equipos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Equipo,Tipo_Equipo")] Equipo equipo)
        {
            if (ModelState.IsValid)
            {
                db.Equipoes.Add(equipo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(equipo);
        }

        // GET: Equipos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipo equipo = db.Equipoes.Find(id);
            if (equipo == null)
            {
                return HttpNotFound();
            }
            return View(equipo);
        }

        // POST: Equipos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Equipo,Tipo_Equipo")] Equipo equipo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(equipo);
        }

        // GET: Equipos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipo equipo = db.Equipoes.Find(id);
            if (equipo == null)
            {
                return HttpNotFound();
            }
            return View(equipo);
        }

        // POST: Equipos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Equipo equipo = db.Equipoes.Find(id);
            db.Equipoes.Remove(equipo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SREA/Views/Dia_Apartado/Create.cshtml
@model SREA.Models.Dia_Apartado

@{
    ViewBag.Title = "Dia Reserva - Reservar";
}

<h2>Ingresar Hora y Dia de Reserva</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Apartada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Apartada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Apartada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora_Comienzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora_Comienzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora_Comienzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora_Terminado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora_Terminado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora_Terminado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Solicitud, "Numero de Solicitud", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Solicitud", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Solicitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Generar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Dia_Apartado")'">Regresar</button>
</div>

SREA/Views/Dia_Apartado/Delete.cshtml
@model SREA.Models.Dia_Apartado

@{
    ViewBag.Title = "Dia de Reservas - Borrar";
}

<h2>Delete</h2>

<h3>¿Esta seguro que quiere eliminar este dia de Reserva?</h3>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Solicitud.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Solicitud.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Apartada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Apartada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hora_Comienzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora_Comienzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hora_Terminado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora_Terminado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
        </div>
    }
</div>

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Dia_Apartado")'">Regresar</button>
</div>

SREA/Views/Dia_Apartado/Details.cshtml
@model SREA.Models.Dia_Apartado

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Solicitud.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Solicitud.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Apartada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Apartada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hora_Comienzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora_Comienzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hora_Terminado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora_Terminado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Regresar", "Index")
</p>

SREA/Views/Dia_Apartado/Edit.cshtml
@model SREA.Models.Dia_Apartado

@{
    ViewBag.Title = "Dia Reserva - Editar";
}

<h2>Editar Dia de Reserva</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Dia_Apartado)

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Apartada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Apartada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Apartada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora_Comienzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora_Comienzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora_Comienzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora_Terminado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora_Terminado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora_Terminado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Solicitud, "Numero de Solicitud", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Solicitud", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Solicitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Dia_Apartado")'">Regresar</button>
</div>

SREA/Views/Dia_Apartado/Index.cshtml
@model SREA.Models.Dia_Apartado

@{
    ViewBag.Title = "Dias de Reserva - Inicio";
}
<h2>Inicio</h2>
<h4>Tipo de Equipos</h4>
<font>En esta Seccion se podra consultar, ingresar, editar y borrar los dias que ha reservado</font>
<hr />
<ul class="list-group">
    <li class="list-group-item active list-group-item-heading"><span class="glyphicon glyphicon-cog"></span><font color="white"> Dia de Reserva</font></li>
    <li class="list-group-item"><span class="glyphicon glyphicon-list-alt"></span>@Html.ActionLink(" Lista Dias Reservados", "Lista", "Dia_Apartado")</li>
    <li class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>@Html.ActionLink(" Agregar Dias Reservados", "Create", "Dia_Apartado")</li>
    <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span>@Html.ActionLink(" Modificar o Eliminar Registro de Dias Reservados", "Modificar", "Dia_Apartado")</li>
</ul>
<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Solicitudes")'">Regresar</button>
</div>

SREA/Views/Dia_Apartado/Lista.cshtml
@model IEnumerable<SREA.Models.Dia_Apartado>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista de Dias Reservados</h2>

<table class="table">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.Solicitud.Tema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Apartada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_Comienzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_Terminado)
        </th>
        <th>Opciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Solicitud.Tema)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Apartada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_Comienzo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_Terminado)
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.ID_Dia_Apartado }) 
            </td>
        </tr>
    }

</table>
<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Dia_Apartado")'">Regresar</button>
</div>

SREA/Views/Dia_Apartado/Modificar.cshtml
@model IEnumerable<SREA.Models.Dia_Apartado>

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar o elimin</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Solicitud.Tema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Apartada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_Comienzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_Terminado)
        </th>
        <th>Opciones</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Solicitud.Tema)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_Apartada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hora_Comienzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hora_Terminado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID_Dia_Apartado }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.ID_Dia_Apartado })
        </td>
    </tr>
}

</table>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Equipos")'">Regresar</button>